[package]
name = "libiguana"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uniffi = { version = "0.25.0", features = [ "cli" ] }

[build-dependencies]
uniffi = { version = "0.25.0", features = [ "build" ] }

[lib]
crate-type = ["cdylib"]
name = "libiguana"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"