name: Publish Swift Package

on:
  push:
    branches:
      - jimulator

jobs:
  swift-package:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile Jimulator
        run: clang++ -O2 -std=c++14 -arch x86_64 -arch arm64 -o jimulator jimulator.cpp
      - name: Strip Jimulator
        run: strip jimulator
      - name: Install cargo-swift
        run: cargo install cargo-swift
      - name: Install Rust targets
        run: rustup target add aarch64-apple-darwin x86_64-apple-darwin
      - name: Build Swift package
        run: cargo swift package --release --name Libiguana --platforms macos
      - name: Patch Package.swift
        run: patch Libiguana/Package.swift < swift-extras/add-binary-resource.diff
      - name: Copy init extension into package
        run: cp swift-extras/IguanaEnvironment+init.swift Libiguana/Sources/Libiguana
      - name: Copy jimulator into Swift package
        run: mkdir Libiguana/Sources/Libiguana/Resources && cp jimulator Libiguana/Sources/Libiguana/Resources
      - name: Checkout libiguana-swift
        uses: actions/checkout@v4
        with:
          repository: iguana-debugger/libiguana-swift
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: libiguana-swift
      - name: Copy Swift package to libiguana-swift
        run: |
          rm -r libiguana-swift/*
          cp -r Libiguana/* libiguana-swift/
          cd libiguana-swift
          git add --all
          git commit -m "Update libiguana-swift from Action"
          git push