name: Publish Swift Package

on:
  push:
    branches:
      - jimulator

jobs:
  swift-package:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile Jimulator
        run: clang++ -O2 -std=c++14 -arch x86_64 -arch arm64 -o jimulator jimulator.cpp
      - name: Strip Jimulator
        run: strip jimulator
      - name: Install cargo-swift
        run: cargo install cargo-swift
      - name: Build Swift package
        run: cargo swift package --release --name Libiguana --platforms macos
      - name: Copy jimulator into Swift package
        run: cp libiguana Libiguana/
      - name: Copy Swift package to repo
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: /Libiguana
          dst_path: /.
          dst_owner: iguana-debugger
          dst_repo_name: libiguana-swift